---
- name: Check CPU
  hosts: all
  gather_facts: no
  vars:
    api_url: "https://api.telegram.org"
    bot_token: "6391730139:AAHzKEP4uwqm_KWZ3sbVDsfR5AnWRB7m0iY"
    chat_id: "526906914"

  tasks:
    - name: Show CPU usage
      ansible.builtin.shell: mpstat
      register: cpu_output

    - name: Send CPU output to Telegram
      ansible.builtin.uri:
        url: "{{ api_url }}/bot{{ bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ chat_id }}"
          text: |
            🖥 Host: {{ inventory_hostname }}
            📊 CPU usage:
            {{ cpu_output.stdout }}
      delegate_to: localhost
